In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/itsm_incident_dataset.csv")
df.head()

,Status,Ticket ID,Priority,Source,Topic,Agent Group,Agent Name,Created time,Expected SLA to resolve,Expected SLA to first response,...,Resolution time,SLA For Resolution,Close time,Agent interactions,Survey results,Product group,Support Level,Country,Latitude,Longitude
0,Closed,TCKT-100000,High,Email,General Inquiry,Security,Khalid Al-Salem,04-07-2024 12.42,04-07-2024 14.42,04-07-2024 13.12,...,04-07-2024 14.30,Met,04-07-2024 14.32,5,Neutral,Cloud,L3,Oman,25.1856,50.9447
1,Closed,TCKT-100001,High,Chat,Network Issue,Customer Service,Ahmed Al-Sabah,23-05-2024 20.03,23-05-2024 22.03,23-05-2024 20.33,...,23-05-2024 22.00,Met,23-05-2024 22.05,4,Dissatisfied,Cloud,L2,Qatar,23.2741,55.3867
2,In Progress,TCKT-100002,Low,Phone,General Inquiry,Development,Mohammed Al-Mansoori,13-04-2024 20.51,14-04-2024 0.51,13-04-2024 21.51,...,14-04-2024 0.47,Met,14-04-2024 0.51,3,Dissatisfied,Software,L1,Bahrain,23.6264,50.1302
3,Resolved,TCKT-100003,Critical,Chat,Access Request,Development,Mohammed Al-Khalifa,13-05-2024 12.50,13-05-2024 13.50,13-05-2024 13.00,...,13-05-2024 13.48,Met,13-05-2024 13.53,5,Dissatisfied,Network,L2,Kuwait,25.0736,54.8437
4,Closed,TCKT-100004,Critical,Portal,Hardware Failure,Customer Service,Hassan Al-Nasser,19-06-2024 22.51,19-06-2024 23.51,19-06-2024 23.01,...,19-06-2024 23.49,Met,19-06-2024 23.54,4,Neutral,Hardware,L3,Qatar,24.7362,51.4839

In [3]:
df.shape

(100000, 22)

In [6]:
df.columns

Index(['Status', 'Ticket ID', 'Priority', 'Source', 'Topic', 'Agent Group',
       'Agent Name', 'Created time', 'Expected SLA to resolve',
       'Expected SLA to first response', 'First response time',
       'SLA For first response', 'Resolution time', 'SLA For Resolution',
       'Close time', 'Agent interactions', 'Survey results', 'Product group',
       'Support Level', 'Country', 'Latitude', 'Longitude'],
      dtype='object')

In [8]:
df.info

<bound method DataFrame.info of             Status    Ticket ID  Priority  Source             Topic  \
0           Closed  TCKT-100000      High   Email   General Inquiry
1           Closed  TCKT-100001      High    Chat     Network Issue
2      In Progress  TCKT-100002       Low   Phone   General Inquiry
3         Resolved  TCKT-100003  Critical    Chat    Access Request
4           Closed  TCKT-100004  Critical  Portal  Hardware Failure
...            ...          ...       ...     ...               ...
99995       Closed  TCKT-199995       Low  Portal     Network Issue
99996  In Progress  TCKT-199996    Medium  Portal      Software Bug
99997  In Progress  TCKT-199997    Medium    Chat  Hardware Failure
99998  In Progress  TCKT-199998      High   Phone  Hardware Failure
99999     Resolved  TCKT-199999      High    Chat   General Inquiry

            Agent Group            Agent Name      Created time  \
0              Security       Khalid Al-Salem  04-07-2024 12.42
1      Customer Service        Ahmed Al-Sabah  23-05-2024 20.03
2           Development  Mohammed Al-Mansoori  13-04-2024 20.51
3           Development   Mohammed Al-Khalifa  13-05-2024 12.50
4      Customer Service      Hassan Al-Nasser  19-06-2024 22.51
...                 ...                   ...               ...
99995          Security     Fahad Al-Mansoori   17-06-2024 7.47
99996          Security  Mohammed Al-Mansoori   10-07-2024 0.39
99997          Security       Khalid Al-Salem  31-05-2024 12.39
99998          Security    Khalid Al-Mansoori  18-04-2024 19.35
99999       Development       Fahad Al-Nasser   12-05-2024 8.22

      Expected SLA to resolve Expected SLA to first response  ...  \
0            04-07-2024 14.42               04-07-2024 13.12  ...
1            23-05-2024 22.03               23-05-2024 20.33  ...
2             14-04-2024 0.51               13-04-2024 21.51  ...
3            13-05-2024 13.50               13-05-2024 13.00  ...
4            19-06-2024 23.51               19-06-2024 23.01  ...
...                       ...                            ...  ...
99995        17-06-2024 11.47                17-06-2024 8.47  ...
99996         10-07-2024 3.39                10-07-2024 1.24  ...
99997        31-05-2024 15.39               31-05-2024 13.24  ...
99998        18-04-2024 21.35               18-04-2024 20.05  ...
99999        12-05-2024 10.22                12-05-2024 8.52  ...

        Resolution time SLA For Resolution        Close time  \
0      04-07-2024 14.30                Met  04-07-2024 14.32
1      23-05-2024 22.00                Met  23-05-2024 22.05
2       14-04-2024 0.47                Met   14-04-2024 0.51
3      13-05-2024 13.48                Met  13-05-2024 13.53
4      19-06-2024 23.49                Met  19-06-2024 23.54
...                 ...                ...               ...
99995  17-06-2024 11.33                Met  17-06-2024 11.34
99996   10-07-2024 3.27                Met   10-07-2024 3.28
99997  31-05-2024 15.29                Met  31-05-2024 15.30
99998  18-04-2024 21.23                Met  18-04-2024 21.26
99999  12-05-2024 10.14                Met  12-05-2024 10.15

      Agent interactions Survey results  Product group Support Level  Country  \
0                      5        Neutral          Cloud            L3     Oman
1                      4   Dissatisfied          Cloud            L2    Qatar
2                      3   Dissatisfied       Software            L1  Bahrain
3                      5   Dissatisfied        Network            L2   Kuwait
4                      4        Neutral       Hardware            L3    Qatar
...                  ...            ...            ...           ...      ...
99995                  2   Dissatisfied          Cloud            L2    Qatar
99996                  1      Satisfied       Software            L2  Bahrain
99997                  1   Dissatisfied       Software            L1   Kuwait
99998                  5      Satisfied       Software            L1    Qatar
99999                  5        Neutral          Cloud            L3  Bahrain

      Latitude Longitude
0      25.1856   50.9447
1      23.2741   55.3867
2      23.6264   50.1302
3      25.0736   54.8437
4      24.7362   51.4839
...        ...       ...
99995  23.1631   53.2074
99996  24.9336   53.6779
99997  23.0871   50.0627
99998  24.5575   52.3957
99999  24.1055   50.4414

[100000 rows x 22 columns]>

In [10]:
df.describe()

       Agent interactions       Latitude      Longitude
count       100000.000000  100000.000000  100000.000000
mean             3.003470      24.002431      53.004252
std              1.415612       1.156356       1.729986
min              1.000000      22.000000      50.000000
25%              2.000000      22.998075      51.502675
50%              3.000000      24.007500      53.005550
75%              4.000000      25.000725      54.504500
max              5.000000      25.999900      55.999900

In [12]:
df.isnull().sum()

Status                            0
Ticket ID                         0
Priority                          0
Source                            0
Topic                             0
Agent Group                       0
Agent Name                        0
Created time                      0
Expected SLA to resolve           0
Expected SLA to first response    0
First response time               0
SLA For first response            0
Resolution time                   0
SLA For Resolution                0
Close time                        0
Agent interactions                0
Survey results                    0
Product group                     0
Support Level                     0
Country                           0
Latitude                          0
Longitude                         0
dtype: int64

In [14]:
df.duplicated(subset="Ticket ID").sum()

np.int64(0)

In [15]:
df.select_dtypes(include="object").nunique()

Status                                 5
Ticket ID                         100000
Priority                               4
Source                                 4
Topic                                  5
Agent Group                            5
Agent Name                            80
Created time                       77910
Expected SLA to resolve            77840
Expected SLA to first response     78000
First response time                77901
SLA For first response                 1
Resolution time                    78103
SLA For Resolution                     1
Close time                         77880
Survey results                         3
Product group                          4
Support Level                          3
Country                                6
dtype: int64

In [16]:
df.sample(5)

,Status,Ticket ID,Priority,Source,Topic,Agent Group,Agent Name,Created time,Expected SLA to resolve,Expected SLA to first response,...,Resolution time,SLA For Resolution,Close time,Agent interactions,Survey results,Product group,Support Level,Country,Latitude,Longitude
33900,Resolved,TCKT-133900,High,Email,Access Request,Network Ops,Hassan Al-Khalifa,09-05-2024 3.55,09-05-2024 5.55,09-05-2024 4.25,...,09-05-2024 5.48,Met,09-05-2024 5.50,1,Dissatisfied,Network,L3,Bahrain,22.3058,55.9582
95877,Open,TCKT-195877,Medium,Email,Software Bug,Development,Yousef Al-Mansoori,26-04-2024 11.17,26-04-2024 14.17,26-04-2024 12.02,...,26-04-2024 14.05,Met,26-04-2024 14.09,1,Dissatisfied,Software,L2,Qatar,23.6454,50.6675
40229,Closed,TCKT-140229,Critical,Portal,Hardware Failure,Network Ops,Ali Al-Khalifa,04-08-2024 20.12,04-08-2024 21.12,04-08-2024 20.22,...,04-08-2024 21.08,Met,04-08-2024 21.13,1,Neutral,Network,L3,Kuwait,23.9625,50.4969
83676,New,TCKT-183676,Medium,Portal,Network Issue,Customer Service,Saif Al-Sabah,03-04-2024 4.20,03-04-2024 7.20,03-04-2024 5.05,...,03-04-2024 7.04,Met,03-04-2024 7.08,1,Neutral,Software,L3,Saudi Arabia,22.0566,55.1063
10976,In Progress,TCKT-110976,Low,Chat,Software Bug,IT Support,Khalid Al-Khalifa,11-04-2024 8.57,11-04-2024 12.57,11-04-2024 9.57,...,11-04-2024 12.53,Met,11-04-2024 12.54,3,Neutral,Cloud,L2,UAE,23.0381,52.0244